apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e3z9cp9nf-python 
  janus-idp.io/tekton: e3z9cp9nf-python
  backstage.io/kubernetes-id: e3z9cp9nf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e3z9cp9nf-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml